# Generated by Django 4.1.4 on 2023-02-03 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("camera", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="camera",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
