# Generated by Django 4.1.4 on 2023-02-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0002_alter_camera_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="fps",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
