# Generated by Django 4.1.4 on 2023-02-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0003_camera_fps"),
    ]

    operations = [
        migrations.RenameField(
            model_name="camera", old_name="camera_name", new_name="name",
        ),
        migrations.RenameField(
            model_name="camera", old_name="rtsp_camera", new_name="rtsp",
        ),
    ]
