# Generated by Django 4.1.6 on 2023-02-13 20:26

import apps.plate.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0005_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('tracking_id', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.plate.models.custom_upload_to)),
                ('content', models.CharField(max_length=10)),
                ('in_frames', models.IntegerField(blank=True, null=True)),
                ('durations', models.FloatField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate', to='camera.camera')),
            ],
        ),
    ]
