# Generated by Django 4.1.6 on 2023-02-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0002_plate_city_plate_state_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='plate',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
