# Generated by Django 4.1.6 on 2023-02-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0003_alter_alert_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='tracking_id',
        ),
        migrations.AlterField(
            model_name='plate',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
