# Generated by Django 4.1.6 on 2023-02-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0004_remove_plate_tracking_id_alter_plate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plate',
            old_name='durations',
            new_name='duration',
        ),
    ]
