# Generated by Django 4.1.6 on 2023-02-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0005_rename_durations_plate_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='in_frames',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
