# Generated by Django 4.1.4 on 2022-12-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user", options={"permissions": (("view_home", "View Home"),)},
        ),
    ]
