# Generated by Django 4.1.4 on 2022-12-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_userprofile_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("view_home", "Visualizar Home"),
                    ("view_content", "Visualizar Content"),
                    ("view_domain", "Visualizar Domain"),
                    ("edit_domain", "Editar Domain"),
                    ("create_domain", "Criar Domain"),
                    ("delete_domain", "Deletar Domain"),
                    ("view_goals", "Visualizar Goals"),
                    ("edit_goals", "Editar Goals"),
                    ("create_goals", "Criar Goals"),
                    ("delete_goals", "Deletar Goals"),
                    ("view_invoice", "Visualizar Invoice"),
                    ("edit_invoice", "Editar Invoice"),
                    ("create_invoice", "Criar Invoice"),
                    ("delete_invoice", "Deletar Invoice"),
                    ("view_kpi", "Visualizar KPI"),
                    ("view_employees", "Visualizar Employees"),
                    ("view_clients", "Visualizar Clients"),
                    ("edit_clients", "Editar Clients"),
                    ("create_clients", "Criar Clients"),
                    ("delete_clients", "Deletar Clients"),
                    ("view_campaings", "Visualizar Campaings"),
                    ("view_users", "Visualizar Users"),
                    ("edit_users", "Editar Users"),
                    ("create_users", "Criar Users"),
                    ("delete_users", "Deletar Users"),
                )
            },
        ),
    ]
