# Generated by Django 4.1.4 on 2022-12-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    ("uc_view_home", "Visualizar Home"),
                    ("uc_view_content", "Visualizar Content"),
                    ("uc_view_domain", "Visualizar Domain"),
                    ("uc_edit_domain", "Editar Domain"),
                    ("uc_create_domain", "Criar Domain"),
                    ("uc_delete_domain", "Deletar Domain"),
                    ("uc_view_goals", "Visualizar Goals"),
                    ("uc_edit_goals", "Editar Goals"),
                    ("uc_create_goals", "Criar Goals"),
                    ("uc_delete_goals", "Deletar Goals"),
                    ("uc_view_invoice", "Visualizar Invoice"),
                    ("uc_edit_invoice", "Editar Invoice"),
                    ("uc_create_invoice", "Criar Invoice"),
                    ("uc_delete_invoice", "Deletar Invoice"),
                    ("uc_view_kpi", "Visualizar KPI"),
                    ("uc_view_employees", "Visualizar Employees"),
                    ("uc_view_clients", "Visualizar Clients"),
                    ("uc_edit_clients", "Editar Clients"),
                    ("uc_create_clients", "Criar Clients"),
                    ("uc_delete_clients", "Deletar Clients"),
                    ("uc_view_campaings", "Visualizar Campaings"),
                    ("uc_view_users", "Visualizar Users"),
                    ("uc_edit_users", "Editar Users"),
                    ("uc_create_users", "Criar Users"),
                    ("uc_delete_users", "Deletar Users"),
                )
            },
        ),
    ]
