# Generated by Django 4.1.4 on 2023-01-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": (("uc_view_dashboard", "Visualizar Dashboard"),)},
        ),
    ]
